version: '3.9'
services:
    openwrt:
        command: "/sbin/init"
        image: registry.cn-shanghai.aliyuncs.com/suling/openwrt:x86_64
        container_name: openwrt
        hostname: openwrt
        volumes:
            - /opt/openwrt/etc:/etc
        privileged: true
        networks:
            network: 
              ipv4_address: 198.19.255.250
        restart: always
networks:
  network:
    driver: macvlan
    driver_opts:
      parent: enp1s0
    ipam:
      config:
        - subnet: "198.19.255.0/24"
          gateway: "198.19.255.254"

