version: '3.9'
services:
   app:
     image: emby/embyserver
     container_name: embyserver
     hostname: embyserver
     volumes:
       #挂载媒体库目录
       - /opt/embyserver/movie:/library/movie
       - /opt/embyserver/tv:/library/tv
       - /opt/embyserver/music:/library/music
       - /opt/embyserver/config:/config
     ports:
       - "8096:8096"
       - "8920:8920"
     privileged: true
     environment:
       - "UID:0"
       - "GID:0"
       - "GIDLIST:0"
     restart: always
