version: '3.3'
services:
  app:
    image: registry.cn-hangzhou.aliyuncs.com/cxlj/openeuler:24.03-lts
    container_name: local_mirrors
    hostname: local_mirrors
    volumes:
      - /opt/mirrors:/opt/mirrors
    privileged: true
    environment:
      - "UID:0"
      - "GID:0"
      - "GIDLIST:0"
    restart: always