version: '3.9'
services:
   db:
     image: mysql:8.0
     container_name: wordpress-db
     hostname: wpdb
     volumes:
       - /opt/wordpress/db:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: P@SsW0rD!#!$*
       MYSQL_DATABASE: mywp
       MYSQL_USER: mywp-user
       MYSQL_PASSWORD: P@SsW0rD!#!$*

   app:
     depends_on:
       - "db"
     image: wordpress:latest
     container_name: wordpress-web
     hostname: wpweb
     volumes:
       - /opt/wordpress/app:/var/www/html
     ports:
       - "10380:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: mywp-user
       WORDPRESS_DB_PASSWORD: P@SsW0rD!#!$*
       WORDPRESS_DB_NAME: mywp
